@startuml
title 换电流程 时序图
用户 -> APP: 扫码
APP -> 服务端: 请求开门
服务端 -> 服务端: 插入并缓存预换电记录[开始]:\n (柜机号, 骑手, 归还舱位(空舱), 归还电池(骑手当前租借电池))
服务端 -> 柜机: 开门指令(归还舱位)
group 柜机开门
    柜机 --> 服务端:
end
note right: 若开门失败, 业务失败
服务端 -> 服务端: 更新换电记录[已开空舱]
note right: [已开空舱]状态下, 用户可通过APP重新打开归还舱位(处理充电失败或未插入充电等问题)

用户 -> 柜机: 放入电池, 插电源线
note right: 每30秒提醒一次用户关门, 超过2分钟未关门 告警
用户 -> 柜机: 关门
柜机 -> 服务端: 舱位属性上报(reportType: lock, lock: true)
group 电池充电
    柜机 --> 服务端:
end
note right: 若充电中上报的电池 不是归还电池, 打开归还舱位, 业务失败(骑手关门)
服务端 -> 服务端: 更新换电记录[已归还]

服务端 -> 服务端: 选取 借出电池 及借出舱位(柜机内最早充满或电量最高的电池 及所在舱位)
服务端 -> 柜机: 开门指令(借出舱位)
group 柜机开门
    柜机 --> 服务端:
end
note right: 若开门失败, 打开归还舱位, 业务失败(骑手关门)
服务端 -> 服务端: 更新换电记录[已借出], 并记录借出电池 借出舱位 \n更新归还电池 所在舱位 及租用骑手 \n更新借出电池 所在舱位 及租用骑手
用户 -> 柜机: 关门
柜机 -> 服务端: 舱位属性上报(reportType: lock, lock: true)
服务端 -> 服务端: 更新换电记录[已完成]


newpage 柜机开门流程
group 柜机开门
    柜机 --> 柜机: 若已通电, 断电
    note right: 三次断电失败, 放弃<柜机开门>, 告警
    柜机 -> 柜机: 充电状态置为[未充电], 灭灯
    柜机 --> 服务端: 若充电状态变化, 舱位属性上报(reportType: charging, charging: un)
    柜机 -> 柜机: 开门
    note right: 三次开门失败, 放弃<柜机开门>, 告警
    柜机 -> 柜机: 开门成功, 门状态置为[开启]
    柜机 --> 服务端: 若锁状态变化, 舱位属性上报(reportType: lock, lock: false)
    柜机 -> 服务端: 回调开门结果
end


newpage 电池充电流程
group 电池充电
    柜机 -> 柜机: 通电
    note right: 三次通电失败, 放弃<电池充电>, 告警, 回调开门结果
    柜机 --> 柜机: 若[未充电]无电流->有电流, 充电状态置为[充电中], 亮红灯
    柜机 --> 服务端: 若充电状态变化, 舱位属性上报(reportType: charging, charging: ing)
    柜机 -> 柜机: 无电流持续10分钟(参数配置) 断电,\n若[充电中], 充电状态为置为[已充满], 亮绿灯
    note right: 三次断电失败 告警, 回调开门结果
    柜机 --> 服务端: 若充电状态变化, 舱位属性上报(reportType: charging, charging: full)
end
@enduml